### PR TITLE
mathwallet providerUrl

### PR DESCRIPTION
**Pull request by yuzhiyou1990**

### CODE REVIEW

**Comment by Zergity** [comment]
I think all browser extensions can share the same wallet name, something like '**injected**' or '**browser extension**'.

Also apply for #46

**Comment by cz-it** [comment]
> I think all browser extensions can share the same wallet name, something like '**injected**' or '**browser extension**'.
> 
> Also apply for #46

For serum-dex-ui , the only interface is wallet.tsx which wrapped sol-wallet-adapter.
When a new Browser Extension comes, such like Solong. It is his responsibility to provider a SOL Wallet Adapter to compatible with sol-wallet-adapter. Here we got solong_adapter. And for serum-dex-ui , It just need to
create different wallet variable for SOL Wallet Adapter of the provider.

Emm... Maybe solong_adapter should be in a independent repo no in serum-dex-ui source directory.

Also apply for #46

**Comment by Zergity** [comment]
> > I think all browser extensions can share the same wallet name, something like '**injected**' or '**browser extension**'.
> > Also apply for #46
> 
> For serum-dex-ui , the only interface is wallet.tsx which wrapped sol-wallet-adapter.
> When a new Browser Extension comes, such like Solong. It is his responsibility to provider a SOL Wallet Adapter to compatible with sol-wallet-adapter. Here we got solong_adapter. And for serum-dex-ui , It just need to
> create different wallet variable for SOL Wallet Adapter of the provider.
> 
> Emm... Maybe solong_adapter should be in a independent repo no in serum-dex-ui source directory.
> 
> Also apply for #46

Creating new sol-wallet-adapter is no longer necessary after sol-wallet-adapter-1.3, a simple extended class that enable the injected interface is sufficient.

```
class InjectedWallet extends Wallet {
  constructor(providerUrl, network) {
    super(providerUrl, network);
    this._useInjectedInterface = true;
  }
}
```

**Comment by cz-it** [comment]
> > > I think all browser extensions can share the same wallet name, something like '**injected**' or '**browser extension**'.
> > > Also apply for #46
> > 
> > 
> > For serum-dex-ui , the only interface is wallet.tsx which wrapped sol-wallet-adapter.
> > When a new Browser Extension comes, such like Solong. It is his responsibility to provider a SOL Wallet Adapter to compatible with sol-wallet-adapter. Here we got solong_adapter. And for serum-dex-ui , It just need to
> > create different wallet variable for SOL Wallet Adapter of the provider.
> > Emm... Maybe solong_adapter should be in a independent repo no in serum-dex-ui source directory.
> > Also apply for #46
> 
> Creating new sol-wallet-adapter is no longer necessary after sol-wallet-adapter-1.3, a simple extended class that enable the injected interface is sufficient.
> 
> ```
> class InjectedWallet extends Wallet {
>   constructor(providerUrl, network) {
>     super(providerUrl, network);
>     this._useInjectedInterface = true;
>   }
> }
> ```

Yep. here SolongAdapter is just a "InjectedWallet" which implement Wallet，suck like method "connect","signTransaction"...etc.

But echo Broswer Extension may have it's own "InjectedWallet"  to implement it's own "connect","signTransaction"...etc.Maybe a "InjectedSolongWallet" or "InjectedMathWallet"

**Comment by Zergity** [comment]
> > > > I think all browser extensions can share the same wallet name, something like '**injected**' or '**browser extension**'.
> > > > Also apply for #46
> > > 
> > > 
> > > For serum-dex-ui , the only interface is wallet.tsx which wrapped sol-wallet-adapter.
> > > When a new Browser Extension comes, such like Solong. It is his responsibility to provider a SOL Wallet Adapter to compatible with sol-wallet-adapter. Here we got solong_adapter. And for serum-dex-ui , It just need to
> > > create different wallet variable for SOL Wallet Adapter of the provider.
> > > Emm... Maybe solong_adapter should be in a independent repo no in serum-dex-ui source directory.
> > > Also apply for #46
> > 
> > 
> > Creating new sol-wallet-adapter is no longer necessary after sol-wallet-adapter-1.3, a simple extended class that enable the injected interface is sufficient.
> > ```
> > class InjectedWallet extends Wallet {
> >   constructor(providerUrl, network) {
> >     super(providerUrl, network);
> >     this._useInjectedInterface = true;
> >   }
> > }
> > ```
> 
> Yep. here SolongAdapter is just a "InjectedWallet" which implement Wallet，suck like method "connect","signTransaction"...etc.
> 
> But echo Broswer Extension may have it's own "InjectedWallet" to implement it's own "connect","signTransaction"...etc.Maybe a "InjectedSolongWallet" or "InjectedMathWallet"

My point is, you don't need InjectedSolongWallet or InjectedMathWallet, just the InjectedWallet (in my code above) will work with any browser extension.

**Comment by cz-it** [comment]
> > > > > I think all browser extensions can share the same wallet name, something like '**injected**' or '**browser extension**'.
> > > > > Also apply for #46
> > > > 
> > > > 
> > > > For serum-dex-ui , the only interface is wallet.tsx which wrapped sol-wallet-adapter.
> > > > When a new Browser Extension comes, such like Solong. It is his responsibility to provider a SOL Wallet Adapter to compatible with sol-wallet-adapter. Here we got solong_adapter. And for serum-dex-ui , It just need to
> > > > create different wallet variable for SOL Wallet Adapter of the provider.
> > > > Emm... Maybe solong_adapter should be in a independent repo no in serum-dex-ui source directory.
> > > > Also apply for #46
> > > 
> > > 
> > > Creating new sol-wallet-adapter is no longer necessary after sol-wallet-adapter-1.3, a simple extended class that enable the injected interface is sufficient.
> > > ```
> > > class InjectedWallet extends Wallet {
> > >   constructor(providerUrl, network) {
> > >     super(providerUrl, network);
> > >     this._useInjectedInterface = true;
> > >   }
> > > }
> > > ```
> > 
> > 
> > Yep. here SolongAdapter is just a "InjectedWallet" which implement Wallet，suck like method "connect","signTransaction"...etc.
> > But echo Broswer Extension may have it's own "InjectedWallet" to implement it's own "connect","signTransaction"...etc.Maybe a "InjectedSolongWallet" or "InjectedMathWallet"
> 
> My point is, you don't need InjectedSolongWallet or InjectedMathWallet, just the InjectedWallet (in my code above) will work with any browser extension.

You mean InjectedWallet determines to invoke different APIs for different browser extension according to pfoviderUrl?

class InjectedWallet extends Wallet {
  constructor(providerUrl, network) {
    super(providerUrl, network);
    this._useInjectedInterface = true;
  }

 connect() {
  if (this.providerUrl = "xxx") {
      windows.xxx.connect(); // windows.xxx.connect is connect API for XXX Browswer Extension
  }
 }
}

**Pull request closed without merging**
